namespace CLP.Entities.Demo
{
    public interface ICountable : IPageObject
    {
        int Parts { get; set; }
        bool IsInnerPart { get; set; }
        bool IsPartsAutoGenerated { get; set; }
    }
}