//using System;
//using System.Linq;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media;
using Classroom_Learning_Partner.ViewModels;
using System.Collections.Generic;


namespace Classroom_Learning_Partner.Views.Modal_Windows
{
    using Catel.Windows.Controls;

    /// <summary>
    /// Interaction logic for CustomizeArrayView.xaml.
    /// </summary>
    public partial class CustomizeArrayView : Window
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomizeArrayView"/> class.
        /// </summary>
        public CustomizeArrayView()
        {
            InitializeComponent();

            //ShowKeyPadCommand = new Command(OnShowKeyPadCommandExecute);
        }

        private void OKButton_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = true;
        }

        //private int EnterRowsHandler(object sender, RoutedEventArgs e)
        //{
        //        KeypadWindowView keyPad = new KeypadWindowView();
        //        keyPad.Owner = Application.Current.MainWindow;
        //        keyPad.WindowStartupLocation = WindowStartupLocation.Manual;
        //        keyPad.Top = 100;
        //        keyPad.Left = 100;
        //        keyPad.ShowDialog();
        //        //if(keyPad.DialogResult == true && keyPad.NumbersEntered.Text.Length > 0)
        //        //{
        //        //    (PageObject as CLPArray).Rows = Int32.Parse(keyPad.NumbersEntered.Text);
        //        //}
                
        //        return Int32.Parse(keyPad.NumbersEntered.Text);
        //}


        /// <summary>
        /// Shows Modal Window Keypad to input Parts manually.
        /// </summary>
        //public Command ShowKeyPadCommand { get; private set; }

        //private void OnShowKeyPadCommandExecute()
        //{
        //    if(App.MainWindowViewModel.IsAuthoring || !(PageObject as CLPStamp).PartsAuthorGenerated)
        //    {
        //        KeypadWindowView keyPad = new KeypadWindowView();
        //        keyPad.Owner = Application.Current.MainWindow;
        //        keyPad.WindowStartupLocation = WindowStartupLocation.Manual;
        //        keyPad.Top = 100;
        //        keyPad.Left = 100;
        //        keyPad.ShowDialog();
        //        if(keyPad.DialogResult == true && keyPad.NumbersEntered.Text.Length > 0)
        //        {
        //            PageObject.Parts = Int32.Parse(keyPad.NumbersEntered.Text);
        //            (PageObject as CLPStamp).PartsAutoGenerated = true;
        //            (PageObject as CLPStamp).PartsInterpreted = false;
        //            (PageObject as CLPStamp).ClearHandWritingPartsStrokes();
        //            if(App.MainWindowViewModel.IsAuthoring)
        //            {
        //                (PageObject as CLPStamp).PartsAuthorGenerated = true;
        //            }
        //        }
        //    }
        //}

    }

}
